[build]
  base = "/"
  publish = "dist"
  command = "npm run generate:version && npm run generate:postmap:prod && npm run build"

[functions]
  directory = "functions"

[context.production]
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true", AWS_LAMBDA_JS_RUNTIME = "nodejs16.x" }

[dev]
  command = 'npm run start'
  port = 9090
  targetPort = 8080