# This is a general lint tasks that lints
# The site whenever we push to the main branch

name: PR Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "PR Lint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: Install Dependencies
        run: npm ci

      - name: Generate Posts
        run: npm run build-posts

      - name: Generate Version
        run: npm run generate-version

      - name: Check Formatting
        run: npm run format

      - name: Check Types
        run: npm run tsc

      - name: ESLint
        run: npm run lint
