# This is a general lint tasks that lints the
# Code of the site.

name: Lint App

on:
  pull_request:
    paths:
      - "src/**/*"
    branches:
      - main

jobs:
  lint:
    name: "Lint App"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: Install UI Dependencies
        run: npm ci

      # - name: Generate Version
      #   run: npm run generate-version

      - name: Check Formatting
        run: npm run format

      - name: Check Types
        run: npm run tsc

      - name: ESLint
        run: npm run lint
